# Generated by Django 4.2 on 2023-04-23 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credor', '0003_alter_credor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0002_alter_endereco_cep_alter_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroContrato', models.CharField(max_length=10)),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
                ('cnpjCpf', models.DecimalField(decimal_places=0, max_digits=14)),
                ('telefone', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('valorDivida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricaoDivida', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('baixada', models.BooleanField(default=False)),
                ('dataBaixa', models.DateTimeField(blank=True, null=True)),
                ('cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credor.credor')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
