# Generated by Django 4.2 on 2023-04-21 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('nomeCredor', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=14)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=2)),
                ('nomeUsuario', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credorId', models.CharField(max_length=10)),
                ('numeroContrato', models.CharField(max_length=10)),
                ('dataRegistro', models.CharField(max_length=100)),
                ('cpnj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('valorDivida', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('usario', models.CharField(max_length=100)),
                ('descricaoDivida', models.CharField(max_length=100)),
                ('cnpjCpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=14)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=2)),
                ('nomeUsuario', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
