# Generated by Django 4.2 on 2023-04-21 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devedor',
            old_name='usario',
            new_name='cpnjCpf',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='nomeUsuario',
        ),
        migrations.RemoveField(
            model_name='devedor',
            name='cnpjCpf',
        ),
        migrations.RemoveField(
            model_name='devedor',
            name='cpnj',
        ),
        migrations.RemoveField(
            model_name='devedor',
            name='nomeUsuario',
        ),
        migrations.AddField(
            model_name='credor',
            name='cpnjCpf',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credor',
            name='usuario',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devedor',
            name='usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credor',
            name='cep',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='cep',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='dataRegistro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='valorDivida',
            field=models.CharField(max_length=100),
        ),
    ]
