# Generated by Django 4.2 on 2023-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_usario_devedor_cpnjcpf_remove_credor_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='cep',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='credor',
            name='cpnjCpf',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='credor',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='cep',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='cpnjCpf',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='valorDivida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
