# Generated by Django 4.2 on 2023-04-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_credor_cep_alter_credor_cpnjcpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credor',
            old_name='cpnjCpf',
            new_name='cnpjCpf',
        ),
    ]
