# Generated by Django 4.2 on 2023-04-30 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCredor', models.CharField(max_length=100)),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnpjCpf', models.DecimalField(decimal_places=0, max_digits=14)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
