# Generated by Django 4.2 on 2023-04-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('credor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
        migrations.AlterField(
            model_name='credor',
            name='telefone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
