# Generated by Django 4.2 on 2023-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='cnpjCpf',
            field=models.CharField(max_length=14),
        ),
    ]
