# Generated by Django 4.2 on 2023-04-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credor', '0002_alter_credor_email_alter_credor_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
