# Generated by Django 4.2 on 2023-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credor', '0003_alter_credor_cnpjcpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
