# Generated by Django 4.2 on 2023-04-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('linha', models.CharField(max_length=100)),
                ('cep', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
